version: "3"
networks:
  app-customer:
    driver: bridge
services:
  front-end:
    build: front-end
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://jakarta-app:8080/jakarta-app/rest/v1
      - API_NOTIFICATION_URL=http://notification-service:9090/v1/emails
    networks:
      - app-customer
  jakarta-app:
    build: jakarta-app
    ports:
      - "8080:8080"
    environment:
      - KAFKA_URL=kafka:9092
      - KAFKA_TOPIC=emails
      - DEFAULT_EMAIL_ADDRESS=batistacpo@gmail.com
    depends_on:
      - kafka
    networks:
      - app-customer
  notification-service:
    build: notification-service
    image: notification-service:1.0.0
    ports:
      - "9090:9090"
    environment:
      - JAVA_OPTS=-Djasypt.encryptor.password=curso**
      - APP_OPTS=--kafka.bootstrap-servers=kafka:9092 --kafka.topic.notification.email=emails
    depends_on:
      - kafka
    networks:
      - app-customer
  zookeeper:
    image: docker.io/bitnami/zookeeper:3
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-customer
  kafka:
    image: docker.io/bitnami/kafka:2
    ports:
      - "9092:9092"
    expose:
      - "9092"
      - "2181"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      - app-customer

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local